
package Views;

import java.awt.Panel;

import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import Controlers.ControlerMain;


public class WPointings extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private static ControlerMain controler;
	

	public WPointings() {
        initComponents();
    }
    
	
    public WPointings(ControlerMain c) {
    	controler = c;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        
        setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jCheckBox1.setText("Show all pointings");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pointing <IDEmp> - <Date>");
        jLabel4.setPreferredSize(new java.awt.Dimension(34, 40));
        jPanel3.add(jLabel4, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText(" In/Out : ");
        jPanel4.add(jLabel1);

        jLabel2.setText(" Hour pointed :");
        jPanel4.add(jLabel2);

        jLabel3.setText(" Hour planned : ");
        jPanel4.add(jLabel3);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>                        

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    
    public void updatePointings(String[] items) {    	
    	jPanel1.remove(jScrollPane2);
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return items.length; }
            public String getElementAt(int i) { return items[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        ListSelectionModel selectionModel = jList1.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
		        ListSelectionModel lsm = (ListSelectionModel)e.getSource();
		        int index = lsm.getSelectedIndices()[0];
		        jLabel4.setText("Pointing " + jList1.getSelectedValue() + " - <Date>");
			}
		});
        
        jScrollPane2.setViewportView(jList1);
        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration                   
}
